import { NextRequest, NextResponse } from "next/server";
import { Connection } from "@solana/web3.js";
import { prisma } from "@/lib/db";
import {
  describeClawPegRecordStatus,
  findPegRecordAddress,
  parseClawPegRecordAccount,
} from "@/lib/clawpeg";
import { getClawPegTraits } from "@/lib/clawpeg-renderer";
import { getClawPegRpcUrl } from "@/lib/env";

export const dynamic = "force-dynamic";

interface RouteContext {
  params: {
    mint: string;
    pegId: string;
  };
}

function getBaseUrl(request: NextRequest) {
  const envBase =
    process.env["NEXT_PUBLIC_CPEG_APP_URL"] ||
    process.env["NEXT_PUBLIC_APP_URL"] ||
    "";
  if (envBase.startsWith("http://") || envBase.startsWith("https://")) {
    return envBase.replace(/\/$/, "");
  }
  return new URL(request.url).origin;
}

export async function GET(request: NextRequest, { params }: RouteContext) {
  const pegId = Number((params.pegId || "").replace(/\.json$/i, ""));
  if (!Number.isInteger(pegId) || pegId < 1) {
    return NextResponse.json({ success: false, error: "Invalid peg id" }, { status: 400 });
  }

  const launch = await prisma.clawPegLaunch
    .findUnique({
      where: { tokenMint: params.mint },
    })
    .catch(() => null);
  if (!launch) {
    return NextResponse.json({ success: false, error: "cPEG collection not found" }, { status: 404 });
  }

  let traits: Record<string, string | number | boolean | null>;
  try {
    traits = getClawPegTraits({
      rendererId: launch.rendererId,
      rendererVersion: launch.rendererVersion,
      collectionSeed: launch.collectionSeed,
      tokenMint: launch.tokenMint,
      pegId,
      params: (launch.rendererParams as Record<string, unknown> | null) || {},
    }) as Record<string, string | number | boolean | null>;
  } catch (traitError) {
    // A renderer mismatch or stale params should not 500 the whole endpoint.
    // Surface an empty trait set so the UI can show "No traits available"
    // instead of an indefinite "loading" state, and keep the rest of the
    // metadata response intact.
    traits = {
      renderer: `${launch.rendererId}@${launch.rendererVersion}`,
      renderer_error: traitError instanceof Error ? traitError.message : "renderer failed",
    };
  }
  const pegRecordAddress = launch.collectionAddress
    ? findPegRecordAddress(launch.collectionAddress, pegId)
    : null;
  const account = pegRecordAddress
    ? await new Connection(getClawPegRpcUrl(), "confirmed").getAccountInfo(pegRecordAddress, "confirmed").catch(() => null)
    : null;
  const record = account?.data ? parseClawPegRecordAccount(Buffer.from(account.data)) : null;

  const name = `${launch.symbol} cPEG #${pegId}`;
  const relativeImage = `/api/cpeg/${launch.tokenMint}/pegs/${pegId}/svg`;
  const base = getBaseUrl(request);
  const metadata = {
    name,
    symbol: launch.symbol,
    description: `${name} is a deterministic cPEG identity generated by Clawdmint.`,
    image: `${base}${relativeImage}`,
    external_url: `${base}/${launch.tokenMint}#peg-${pegId}`,
    attributes: Object.entries(traits).map(([trait_type, value]) => ({ trait_type, value })),
    properties: {
      category: "image",
      files: [{ uri: `${base}${relativeImage}`, type: "image/svg+xml" }],
    },
  };

  if (request.nextUrl.searchParams.get("format") !== "cpeg") {
    return NextResponse.json(metadata, {
      headers: {
        "Cache-Control": "public, max-age=300, s-maxage=300",
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "GET, OPTIONS",
        "Access-Control-Allow-Headers": "Content-Type, Accept",
        "Cross-Origin-Resource-Policy": "cross-origin",
      },
    });
  }

  if (launch.standardMode === "metaplex_hybrid") {
    const asset = await prisma.clawPegHybridAsset
      .findFirst({
        where: { launchId: launch.id, pegId },
      })
      .catch(() => null);
    return NextResponse.json({
      success: true,
      peg: {
        id: pegId,
        name,
        token_mint: launch.tokenMint,
        collection_address: launch.hybridCoreCollectionAddress || launch.collectionAddress,
        peg_record: asset?.assetAddress || null,
        asset_address: asset?.assetAddress || null,
        minted: Boolean(asset),
        owner: asset?.ownerAddress || null,
        status: asset?.status || null,
        on_chain_seed: String(traits.seed || ""),
        minted_slot: asset?.capturedAt?.toISOString() || "Metaplex Core",
        transferred_slot: asset?.releasedAt?.toISOString() || null,
        burned_slot: "Not applicable",
        image: relativeImage,
        traits,
      },
    });
  }

  return NextResponse.json({
    success: true,
    peg: {
      id: pegId,
      name,
      token_mint: launch.tokenMint,
      collection_address: launch.collectionAddress,
      peg_record: pegRecordAddress?.toBase58() || null,
      minted: Boolean(record?.isInitialized),
      owner: record?.owner || null,
      status: record ? describeClawPegRecordStatus(record.status) : null,
      on_chain_seed: record?.seed || null,
      minted_slot: record?.mintedSlot.toString() || null,
      transferred_slot: record?.transferredSlot.toString() || null,
      burned_slot: record?.burnedSlot.toString() || null,
      image: relativeImage,
      traits,
    },
  });
}

export async function OPTIONS() {
  return new NextResponse(null, {
    status: 204,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type, Accept",
      "Access-Control-Max-Age": "86400",
    },
  });
}
